name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: true

    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: yarn --frozen-lockfile
      - name: setup git
        run: git remote set-url origin https://${{ GITHUB_ACTOR }}:${{ GITHUB_TOKEN }}@github.com/${{ GITHUB_REPOSITORY }}
      - name: deploy
        run: yarn deploy
